// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/dht.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DhtService_Put_FullMethodName          = "/dht.DhtService/Put"
	DhtService_Get_FullMethodName          = "/dht.DhtService/Get"
	DhtService_Delete_FullMethodName       = "/dht.DhtService/Delete"
	DhtService_GetPeers_FullMethodName     = "/dht.DhtService/GetPeers"
	DhtService_AnnouncePeer_FullMethodName = "/dht.DhtService/AnnouncePeer"
)

// DhtServiceClient is the client API for DhtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DhtService exposes the Kademlia DHT operations to external clients
// (e.g., a Rust/C++ BitTorrent client) via gRPC.
type DhtServiceClient interface {
	// Put stores a key-value pair in the DHT.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Get retrieves a value by key from the DHT.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Delete removes a key-value pair from the DHT.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// GetPeers finds peers for a given info_hash.
	// Returns peers if known, otherwise returns closest DHT nodes.
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	// AnnouncePeer registers the caller as a downloader/seeder for an info_hash.
	AnnouncePeer(ctx context.Context, in *AnnouncePeerRequest, opts ...grpc.CallOption) (*AnnouncePeerResponse, error)
}

type dhtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDhtServiceClient(cc grpc.ClientConnInterface) DhtServiceClient {
	return &dhtServiceClient{cc}
}

func (c *dhtServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, DhtService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhtServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, DhtService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhtServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, DhtService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhtServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, DhtService_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhtServiceClient) AnnouncePeer(ctx context.Context, in *AnnouncePeerRequest, opts ...grpc.CallOption) (*AnnouncePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnouncePeerResponse)
	err := c.cc.Invoke(ctx, DhtService_AnnouncePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DhtServiceServer is the server API for DhtService service.
// All implementations must embed UnimplementedDhtServiceServer
// for forward compatibility.
//
// DhtService exposes the Kademlia DHT operations to external clients
// (e.g., a Rust/C++ BitTorrent client) via gRPC.
type DhtServiceServer interface {
	// Put stores a key-value pair in the DHT.
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Get retrieves a value by key from the DHT.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Delete removes a key-value pair from the DHT.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// GetPeers finds peers for a given info_hash.
	// Returns peers if known, otherwise returns closest DHT nodes.
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	// AnnouncePeer registers the caller as a downloader/seeder for an info_hash.
	AnnouncePeer(context.Context, *AnnouncePeerRequest) (*AnnouncePeerResponse, error)
	mustEmbedUnimplementedDhtServiceServer()
}

// UnimplementedDhtServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDhtServiceServer struct{}

func (UnimplementedDhtServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDhtServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDhtServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDhtServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedDhtServiceServer) AnnouncePeer(context.Context, *AnnouncePeerRequest) (*AnnouncePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnouncePeer not implemented")
}
func (UnimplementedDhtServiceServer) mustEmbedUnimplementedDhtServiceServer() {}
func (UnimplementedDhtServiceServer) testEmbeddedByValue()                    {}

// UnsafeDhtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DhtServiceServer will
// result in compilation errors.
type UnsafeDhtServiceServer interface {
	mustEmbedUnimplementedDhtServiceServer()
}

func RegisterDhtServiceServer(s grpc.ServiceRegistrar, srv DhtServiceServer) {
	// If the following call panics, it indicates UnimplementedDhtServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DhtService_ServiceDesc, srv)
}

func _DhtService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhtServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhtService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhtServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhtService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhtServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhtService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhtServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhtService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhtServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhtService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhtServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhtService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhtServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhtService_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhtServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhtService_AnnouncePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnouncePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhtServiceServer).AnnouncePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhtService_AnnouncePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhtServiceServer).AnnouncePeer(ctx, req.(*AnnouncePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DhtService_ServiceDesc is the grpc.ServiceDesc for DhtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DhtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dht.DhtService",
	HandlerType: (*DhtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _DhtService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DhtService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DhtService_Delete_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _DhtService_GetPeers_Handler,
		},
		{
			MethodName: "AnnouncePeer",
			Handler:    _DhtService_AnnouncePeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dht.proto",
}
